name: TestingTravisCI
channels:
- defaults
dependencies:
- python=3.5
- numpy==1.13.1
- jupyter==1.0
- pytest==3.1.3
- requests
- tabulate
- pandas
- pytest-cov
- coveralls
- flake8
- matplotlib
- win32com.client
